### PR TITLE
V2: Add workerSrc prop for better CSP support

### PR DESCRIPTION
**Pull request by mispencer**
Problem: 
Currently, the worker script is being loaded as a data: url. When CSP is limiting scripts, this will fail unless you enabled data: urls, which is strongly discouraged.

Fix:
Allow supplying a worker src in a prop. This allows using a url, and that url can be added to CSP in a strongly targeted matter. Note, however, that this likely only works if added to the first loaded component's props, and that the embedded script remains in the final Javascript as non-trivially sized dead code.

### CODE REVIEW

**Comment by hrynko** [comment]
Hi @mispencer,

Thanks for opening this PR, I guess it's related to #90, which has been tabled for quite a while.

> This allows using a url, and that url can be added to CSP in a strongly targeted matter.

Could you share an example config?

> Note, however, that this likely only works if added to the first loaded component's props.

I'm not sure I understood correctly, could you comment on this?

**Comment by mispencer** [comment]
The key point is that Vite is compiling the worker script from pdfjs-dist into an variable containing the source code of the worker and, at runtime, it attempts to load the worker by creating a script tag with a data: url using that variable. If the site has CSP restriction on script src, this will be blocked unless the CSP rules allow loading script from data schema urls, which is strongly discouraged as this is essentially turning off CSP protection.

However, if you built and hosted the worker script elsewhere, you can set the worker url by use of this new prop to a real url, which can be allowed in a more specific CSP rule, either by the full path or, more likely, by the domain.

It likely only works if set on the first usage because it is setting pdf.GlobalWorkerOptions which is presumably global, not per-instance.

**Comment by hrynko** [comment]
> It likely only works if set on the first usage because it is setting pdf.GlobalWorkerOptions which is presumably global, not per-instance.

But there should be no problem passing `workerSrc` to each instance, right?

**Comment by mispencer** [comment]
I am not an expert on PDF.js, but I assume there is a single global worker shared access all instances.

**Review by hrynko — CHANGES_REQUESTED** [review]
Makes sense, I might revisit it eventually, but it's a good start

Please resolve the conflicts and it can be merged

**Comment by mispencer** [comment]
The conflict has been resolved.

**Comment by hrynko** [comment]
Thank you!

**Pull request merged**
