### PR TITLE
V2: Lint fixes

### PR DESCRIPTION
**Pull request by mispencer**
~~Problem: The documentation (in README) and the implementation use isWrongPassword, but the emit spec uses retry
Fix: Make emit spec match documentation and implementation. Note, however, that this differs from V2.~~

Problem: Eslint checks dist, which likely fails eslint checks
Fix: Exclude dist from eslint

Problem: Nesting under a directory with existing eslint rules has interesting interactions
Fix: Add root to eslint config

### CODE REVIEW

**Comment by hrynko** [comment]
Hi @mispencer,

The type issue seems to be already fixed. As for the ESLint ignore pattern, can you describe a case where it's relevant? For me it looks redundant, since the `lint` script in `packages.json` leverages `.gitignore` (which  includes `dist`) and pre-commit hook doesn't apply to `dist` since it's never committed.

**Comment by mispencer** [comment]
I was running eslint manually in a folder containing this project and it returned errors from this project's dist folder.

**Comment by hrynko** [comment]
Ok I see, but what what is the motivation to run ESLint manually?

**Comment by mispencer** [comment]
I had it as a git submodule in an another project (because there isn't a release in NPM for v2), and was running eslint in that project.

**Review by hrynko — COMMENTED** [review]
Well, it is not recommended to run ESLint manually, and adding their own `ignorePatterns` for ESLint and Prettier (which is also needed in such a case) seems redundant

**Pull request closed without merging**
